server:
  port: 8080
  mode: debug  # debug or release
  read_timeout: 60  # 读取超时时间（秒）
  write_timeout: 60 # 写入超时时间（秒）

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: root
  dbname: k8s_controller
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

log:
  level: debug  # debug, info, warn, error
  filename: ./logs/app.log
  max_size: 100    # 单个日志文件最大尺寸，单位MB
  max_age: 30      # 日志文件保留天数
  max_backups: 10  # 保留的旧日志文件最大数量
  compress: true   # 是否压缩



Logger:
  level: "info"        # 日志级别
  filename: "logs/app.log"  # 日志文件路径
  max-size: 100        # 单个日志文件最大尺寸，单位MB
  max-backups: 10      # 最大保留日志文件数量
  max-age: 30          # 日志文件保留天数
  compress: true       # 是否压缩